### ISSUE TITLE
アプリの見た目のモダン化

### ISSUE THREAD

**Issue by masatanish** [ayabe2000/nutrition_app#28]
今のアプリでは、HTMLに対して装飾がまったくないため、あまり格好がよくありません。
HTMLの見た目を変える機能としてCSSというものがあります。
CSSについて少し勉強してみたうえで、cssフレームワークを導入してみましょう。

- CSSとは何か
- CSSにおけるclassとは何か

あたりが分かれば、以下の課題ができると思います。

TailwindというCSSフレームワークを導入し、みためを格好良くしてみてください。

 [Tailwindの使い方ページ](https://tailwindcss.com/docs/installation/play-cdn)

```html
  <script src="https://cdn.tailwindcss.com"></script>
```
をtemplateのHTMLに追加した上で、 <div>や<input> などにclassを追加し、見た目を良くしてみてください。

この課題を実行する前に、各画面の見た目をスクリーンショットを撮って、このIssueにアップロードしてください。

# TODO
- [x] 各画面のスクリーンショットをこのIssueにアップする
- [x] CSSについて勉強する
- [x] Tailwindを導入してみる
- [x] Tailwindを使って見た目を改善してみる
- [x] 改善後のスクリーンショットをIssueにアップする

**Comment by ayabe2000** [comment]
![スクリーンショット 2023-09-19 143013](https://github.com/ayabe2000/nutrition_app/assets/144399214/837b759e-faa3-426e-94fc-dc6302b3848b)
![スクリーンショット 2023-09-19 143556](https://github.com/ayabe2000/nutrition_app/assets/144399214/8212f3c7-6e04-4833-9fe0-c91433c5ead9)
![スクリーンショット 2023-09-19 143646](https://github.com/ayabe2000/nutrition_app/assets/144399214/1a48b41d-3aad-43d7-bc6e-0ee072401097)

**Comment by ayabe2000** [comment]
![スクリーンショット 2023-09-19 170701](https://github.com/ayabe2000/nutrition_app/assets/144399214/b6dc91d1-bb61-4941-90b5-15b286602243)
![スクリーンショット 2023-09-19 170828](https://github.com/ayabe2000/nutrition_app/assets/144399214/133443a7-c631-4062-8483-83986b76b67c)
![スクリーンショット 2023-09-19 170846](https://github.com/ayabe2000/nutrition_app/assets/144399214/59c4130b-82c2-4de0-b2fc-1d100d611cb7)
