### ISSUE TITLE
データインポートの整理

### ISSUE THREAD

**Issue by masatanish** [ayabe2000/nutrition_app#36]
食品の入力がこむぎ、おくらなどソース上に記述されたものしか選べません
また、これら選択可能な食品(`Food`) は  add_food_data.py でインポートされるようになっており、Excelに記載された食品を選ぶようにはなっていません。(add_food_data.pyについてはREADMEに記載がありませんが)
実質Excelでインポートされた情報は利用されていないのが現状だと思います。

ただ、Excelは同じ食品でも色々な状態で複数登録されており、Excelの食品をユーザに選択してもらうのも現実的ではありません。
食品入力をテキスト領域にして、インクリメンタルサーチを実現すれば可能だと思いますが、技術的にJavaScriptなど新しい要素を色々勉強しないと実現できないので難しいと思います。

この問題をどう扱うかは考える必要があります。(どこかでディスカッションしましょう)

**Comment by masatanish** [comment]
とりあえず、以下の方針で対応しましょう。

1. 食品入力時の選択肢は、 `Food` に登録されている食品から選択できるようにしてください
2. `Food` にexcelファイルのA列(食品群)のデータを追加してください
  - 食品 群は次のpdfに定義されていました(http://www.tokyokyogakusha.com/files/%E3%82%A4%E3%83%A9%E3%82%B9%E3%83%88%E9%A3%9F%E5%93%81%E5%AD%A6%E7%B7%8F%E8%AB%962021%E8%B3%87%E6%96%99.pdf)
3. `FoodEntry`の作成・編集時は食品群の選択→ 食品の選択 とするようにしてください

**Comment by ayabe2000** [comment]
昨日時間があったのでインクリメンタルサーチを利用して選択してもらうように修正し、現在重複したコードの削除など行っているのですが、
上記の方針に変更したほうがよろしいでしょうか。
