### ISSUE TITLE
ユニットテストの導入

### ISSUE THREAD

**Issue by masatanish** [ayabe2000/nutrition_app#46]
ユニットテストとは何かはまず勉強してみてください。
そのうえで、ユニットテストフレームワーク pytestをインストールしてください。

models.pyの`get_food_by_name` と `create_new_food_entry` に対するテストを記載してください。

**Comment by ayabe2000** [comment]
質問があります。
test_models.pyを作成して pytest test_models.pyを実行すると
 ```
____________________________________________ test_create_new_food_entry _____________________________________________

test_client = <FlaskClient <Flask 'app'>>

    def test_create_new_food_entry(test_client):
        food_name = "NewTestFood"
        grams = 100
        user_id = 1
        selected_date = "2023-09-25"

        with app.app_context():
>           create_new_food_entry(food_name, grams, user_id, selected_date)
E           TypeError: create_new_food_entry() missing 1 required positional argument: 'selected_date'

test_models.py:28: TypeError
```
と出てしまい、引数 selected_date が提供されていないことが示されてしまいます。
create_new_food_entry 関数の引数がすべて提供されているか確認したのですが、変化はありません。
どこを確認すべきか教えていただけますでしょうか。
よろしくお願いいたします。

**Comment by masatanish** [comment]
> 引数 selected_date が提供されていないことが示されてしまいます。

エラーメッセージに出ているとおりではないでしょうか。
`create_new_food_entry()` は5つの引数をとるように定義されていますが、4つしか指定されていないように見えます。

```python
def create_new_food_entry(food, food_name, grams, user_id, selected_date):
```

**Comment by ayabe2000** [comment]
ご回答ありがとうございます。上記の件は解決できました。

テストを行っている際に以前は食品名とグラム数を入力して１日の栄養素や履歴に表示できるようになっていたのですが、現状のmainブランチの状態ですと、入力しても出力できない状態になってしまいました。

以前利用していたREADME.md-20ブランチで動作確認したところ問題なく動作しました。
foodのレコードを表示させたところ問題なく表示され、フードエントリーのレコードが表示されない状態です。

各ブランチで作業した際は動作したのでマージさせた際に不具合があったと考えたのですが、どの変更でエラーになったのか確認方法などはありますでしょうか。

**Comment by ayabe2000** [comment]
お忙しいところすみません。質問がございます。
ユニットテストの導入の作業をしている際に特に大きな変更をしていないのに急にテーブルがなくなってしまい、マイグレーションを新しく生成し直せば問題なく作業できますが、なぜテーブルが破損してしまうのでしょうか。
よろしくお願いいたします。

**Comment by ayabe2000** [comment]
解決しました。
ありがとうございます。

**Comment by masatanish** [comment]
環境変数でテストかそうじゃないかを分けてください。
その上でテストではtearDownでdbの消去はしてください。
